---
deployment:
  tasks:
    - export DEPLOYPATH=/home/orderyhd/public_html/orderdashboard/
    - cp *.html $DEPLOYPATH
    - cp *.png $DEPLOYPATH
    - cp *.jpg $DEPLOYPATH
    - cp *.gif $DEPLOYPATH
    - cp *.css $DEPLOYPATH
    - cp *.json $DEPLOYPATH
    - cp *.js $DEPLOYPATH
