---
deployment:
  tasks:
    - export DEPLOYPATH=/home/orderyhd/public_html/orderdashboard/
    - cp *.html $DEPLOYPATH
    - cp *.png $DEPLOYMENTPATH
    - cp *.json $DEPLOYMENTPATH
    - cp *.js $DEPLOYMENTPATH
