[
  { "type": "title", "data": "Plan Name" },
  { "type": "category", "data": "Admit/Transfer/Discharge" },
  { "type": "sentence", "data": "None" },
  {
    "type": "note",
    "data": "Complete pre-induction safety checklist ",
    "value": ""
  },
  { "type": "sentence", "data": "None" },
  { "type": "order", "data": "Admit as inpatient", "value": "checked" },
  { "type": "sentence", "data": "None" },
  { "type": "category", "data": "Consults/Referrals" },
  { "type": "sentence", "data": "None" },
  { "type": "order", "data": "Obstetrics", "value": "" },
  { "type": "sentence", "data": "None" },
  { "type": "category", "data": "Diet/Nutrition" },
  { "type": "sentence", "data": "None" },
  { "type": "order", "data": "Diet as tolerated", "value": "checked" },
  { "type": "sentence", "data": "None" },
  { "type": "order", "data": "Clear fluids", "value": "" },
  { "type": "sentence", "data": "None" },
  { "type": "order", "data": "Ice chips", "value": "" },
  { "type": "sentence", "data": "None" },
  { "type": "order", "data": "NPO", "value": "" },
  { "type": "sentence", "data": "None" },
  { "type": "category", "data": "Activity" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "category", "data": "Patient Care" },
  { "type": "sentence", "data": "None" },
  { "type": "order", "data": "Vitals", "value": "" },
  {
    "type": "sentence",
    "data": "At admission, prior to first misoprostol dose, 30 minutes post first dose, then q2 hours and prn until in active labour"
  },
  { "type": "order", "data": "Uterine activity", "value": "" },
  {
    "type": "sentence",
    "data": "Assess uterine activity and tone by palpation."
  },
  { "type": "order", "data": "Notify MRP", "value": "" },
  { "type": "sentence", "data": "If tachystole" },
  { "type": "order", "data": "Notify MRP", "value": "" },
  { "type": "sentence", "data": "If in active labour" },
  { "type": "order", "data": "Notify MRP", "value": "" },
  { "type": "sentence", "data": "Prior to each dose of misoprostol" },
  { "type": "order", "data": "Non stress test", "value": "" },
  { "type": "sentence", "data": "At admission" },
  { "type": "order", "data": "Non stress test", "value": "" },
  { "type": "sentence", "data": "Prior to first dose of misoprostol" },
  {
    "type": "order",
    "data": "Continuous Electronic Fetal Monitoring",
    "value": ""
  },
  {
    "type": "sentence",
    "data": "For 20 minutes following each dose of misprostol"
  },
  {
    "type": "order",
    "data": "Continuous Electronic Fetal Monitoring",
    "value": ""
  },
  {
    "type": "sentence",
    "data": "For 60 minutes after an episode of tachysystole"
  },
  { "type": "order", "data": "Intermittent auscultation", "value": "" },
  { "type": "sentence", "data": "prn, and q__hr until active labour" },
  { "type": "category", "data": "Laboratory" },
  { "type": "sentence", "data": "None" },
  { "type": "order", "data": "CBC", "value": "" },
  { "type": "sentence", "data": "None" },
  { "type": "order", "data": "Group and screen", "value": "" },
  { "type": "sentence", "data": "None" },
  { "type": "order", "data": "Syphillis screen", "value": "" },
  { "type": "sentence", "data": "None" },
  { "type": "category", "data": "Continuous Infusion" },
  { "type": "sentence", "data": "None" },
  { "type": "order", "data": "0.9% sodium chloride", "value": "" },
  { "type": "sentence", "data": "100 mL/hr" },
  { "type": "sentence", "data": "other options" },
  { "type": "order", "data": "Ringers Lactate", "value": "" },
  { "type": "sentence", "data": "100 mL/hr" },
  { "type": "sentence", "data": "other options" },
  { "type": "order", "data": "Saline lock", "value": "" },
  { "type": "sentence", "data": "None" },
  { "type": "category", "data": "Medications" },
  { "type": "sentence", "data": "None" },
  {
    "type": "note",
    "data": "In large 20 or 60 mL syringe, dissolve 100 micrograms of misoprostol in 20 mL of warm water yielding a concentration of 5 micrograms/mL (stable for 24 hours).",
    "value": ""
  },
  { "type": "sentence", "data": "None" },
  { "type": "note", "data": "Initial dose", "value": "" },
  { "type": "sentence", "data": "None" },
  { "type": "order", "data": "Misoprostol", "value": "" },
  {
    "type": "sentence",
    "data": "20-25 mcg (4-5ml), PO, once, drug form: solution 5 micrograms/mL"
  },
  { "type": "note", "data": "Titration dosing", "value": "" },
  { "type": "sentence", "data": "None" },
  { "type": "order", "data": "Misoprostol", "value": "" },
  {
    "type": "sentence",
    "data": "20-25 mcg (4-5ml), PO, q2 hours, drug form: solution 5 micrograms/mL"
  },
  {
    "type": "note",
    "data": "When active labour established, notify MRP. MRP is not required to switch from misoprostol to oxytocin, as continuing with misoprostol may be more effective.",
    "value": ""
  },
  { "type": "sentence", "data": "None" },
  {
    "type": "note",
    "data": "If active labour not established withing 24 hours (12 does of misoprostol q2hr) consider alternative methods of induction.",
    "value": ""
  },
  { "type": "sentence", "data": "None" },
  { "type": "note", "data": "If tachystole", "value": "" },
  { "type": "sentence", "data": "None" },
  { "type": "order", "data": "nitroglycerine", "value": "" },
  {
    "type": "sentence",
    "data": "50 micrograms IV q90 seconds - 3 minutes PRN to max dose of 200 micrograms over 25 minutes"
  },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" },
  { "type": "sentence", "data": "None" }
]
