[
  { type: "title", data: "PAL Symptom Management (Module)" },
  { type: "category", data: "Admit/Transfer/Discharge" },
  {
    type: "note",
    data: "Provider to discuss prognosis and goals of care with patient or substitute decision maker and document",
  },
  { type: "order", data: "Resuscitation Status", value: "" },
  { type: "sentence", data: "T;N, No CPR, Constant Order" },
  { type: "sentence", data: "T;N, Full Resuscitation, Constant Order" },
  { type: "sentence", data: "T;N, Do Not Resuscitate, Constant Order" },
  { type: "category", data: "Patient Care" },
  {
    type: "note",
    data: "for moderate to severe restlessness/agitation, regularly reassess if medication still required if underlying cause resolves.",
  },
  { type: "order", data: "Communication Order", value: "checked" },
  {
    type: "sentence",
    data: "T;N, Constant Order, BID Use appropriate screening tool for anxiety screen",
  },
  { type: "order", data: "Communication Order", value: "checked" },
  {
    type: "sentence",
    data: "T;N, Constant Order, Use appropriate screening tool for depression screen daily",
  },
  {
    type: "order",
    data: "Confusion Assessment Method (CAM)",
    value: "checked",
  },
  { type: "sentence", data: "T;N, BID" },
  { type: "order", data: "Oral Hygiene", value: "" },
  { type: "sentence", data: "T;N, QID, PRN Order" },
  { type: "order", data: "Skin Care Protocol", value: "" },
  {
    type: "sentence",
    data: "T;N, Constant Order, Assess skins surfaces daily",
  },
  { type: "order", data: "Oxygen Therapy (O2)", value: "" },
  { type: "sentence", data: "T;N, Nasal Cannula, 95 to 100%, Constant Order" },
  { type: "sentence", data: "T;N, Face Mask, 95 to 100%, Constant Order" },
  { type: "order", data: "Urinary Catheter Insertion", value: "" },
  { type: "sentence", data: "T;N, Foley Catheter" },
  { type: "category", data: "Diet/Nutrition" },
  { type: "order", data: "Advance Diet as Tolerated (DAT)", value: "" },
  { type: "order", data: "Diet per Dietitian", value: "" },
  { type: "order", data: "NPO", value: "" },
  { type: "category", data: "Medications" },
  { type: "note", data: "For fever or pain" },
  { type: "order", data: "acetaminophen", value: "" },
  {
    type: "sentence",
    data: "650 mg, PO, Tab, q4hr, PRN, Pain / Fever, Routine, T;N",
  },
  {
    type: "sentence",
    data: "650 mg, PR, Supp, q4hr, PRN, Pain / Fever, Routine, T;N",
  },
  {
    type: "note",
    data: "Choose ONE of the opioids &amp;#10;&amp;#13;&amp;#10;Total 24 hour subcutaneous dose =  half of total 24 hour PO dose&amp;#10;PRN breakthrough dose should be 10% of total regular 24h opioid dose&amp;#10;Use same opioid for regular and breakthrough dose (does not apply to fentaNYL patch or methadone)&quot;",
  },
  { type: "order", data: "morphine", value: "" },
  { type: "sentence", data: "5 mg, PO, Tab, q4hr(sched), Routine, T;N" },
  { type: "sentence", data: "10 mg, PO, Tab, q4hr(sched), Routine, T;N" },
  {
    type: "sentence",
    data: "2.5 mg, SubQ, Injection, q4hr(sched), Routine, T;N",
  },
  {
    type: "sentence",
    data: "5 mg, SubQ, Injection, q4hr(sched), Routine, T;N",
  },
  { type: "order", data: "morphine", value: "" },
  {
    type: "sentence",
    data: "5 mg, PO, Tab, q1hr, PRN, Other (see Comment), Routine, T;N",
  },
  {
    type: "sentence",
    data: "2.5 mg, SubQ, Injection, q30min, PRN, Other (see Comment), Routine, T;N",
  },
  { type: "order", data: "HYDROmorphone", value: "" },
  { type: "sentence", data: "1 mg, PO, Tab, q4hr(sched), Routine, T;N" },
  { type: "sentence", data: "2 mg, PO, Tab, q4hr(sched), Routine, T;N" },
  {
    type: "sentence",
    data: "0.5 mg, SubQ, Injection, q4hr(sched), Routine, T;N",
  },
  {
    type: "sentence",
    data: "1 mg, SubQ, Injection, q4hr(sched), Routine, T;N",
  },
  { type: "order", data: "HYDROmorphone", value: "" },
  {
    type: "sentence",
    data: "1 mg, PO, Tab, q1hr, PRN, Other (see Comment), Routine, T;N",
  },
  {
    type: "sentence",
    data: "0.5 mg, SubQ, Injection, q30min, PRN, Other (see Comment), Routine, T;N",
  },
  { type: "order", data: "LORazepam", value: "" },
  { type: "sentence", data: "1 mg, SL, Tab, q2hr, PRN, Anxiety, Routine, T;N" },
  { type: "order", data: "metoclopramide", value: "" },
  {
    type: "sentence",
    data: "10 mg, PO, Tab, QID, PRN, Nausea or Vomiting, Routine, T;N",
  },
  {
    type: "sentence",
    data: "10 mg, SubQ, Injection, QID, PRN, Nausea or Vomiting, Routine, T;N",
  },
  { type: "order", data: "haloperidol", value: "" },
  {
    type: "sentence",
    data: "1.5 mg, PO, Tab, q8hr, PRN, Nausea &amp; Vomiting, Routine, T;N",
  },
  {
    type: "sentence",
    data: "1.5 mg, SubQ, Injection, q8hr, PRN, Nausea &amp; Vomiting, Routine, T;N",
  },
  {
    type: "note",
    data: "Moderate to severe restlessness / agitation (choose ONE of haloperidol OR methotrimeprazine))",
  },
  { type: "note", data: "Regularly reassess management" },
  { type: "order", data: "haloperidol", value: "" },
  {
    type: "sentence",
    data: "2 mg, PO, Tab, q1hr, PRN, Other (see Comment), Routine, T;N, For moderate to severe restlessness/agitation. Up to 3 doses per event. If not settled after 3 doses, contact prescriber.",
  },
  {
    type: "sentence",
    data: "2 mg, SubQ, Injection, q1hr, PRN, Other (see Comment), Routine, T;N, For moderate to severe restlessness/agitation. Up to 3 doses per event. If not settled after 3 doses, contact prescriber.",
  },
  { type: "order", data: "methotrimeprazine", value: "" },
  {
    type: "sentence",
    data: "25 mg, SubQ, Injection, q1hr, PRN, Other (see Comment), Routine, T;N, May give 12.5 to 25 mg. For moderate to severe restlessness/agitation. Up to 3 doses per event. If not settled after 3 doses, contact prescriber.",
  },
  {
    type: "note",
    data: "End of life upper respiratory secretions/congestion ",
  },
  { type: "order", data: "glycopyrrolate", value: "" },
  {
    type: "sentence",
    data: "0.4 mg, SubQ, Injection, q4hr, PRN, Other (see Comment), Routine, T;N, May give 0.2 to 0.4 mg  For upper respiratory secretions / congestion",
  },
  { type: "order", data: "ocular lubricant ophthalmic solution", value: "" },
  {
    type: "sentence",
    data: "2 drop(s), Eye(s) Both, Ophth Drops, q1hr, PRN, Dry Eyes, 180 day(s)",
  },
  {
    type: "order",
    data: "lidocaine 2% topical gel with applicator",
    value: "",
  },
  {
    type: "sentence",
    data: "1 app, Topically, Jelly, Daily, PRN, Catheter insertion, 180 day(s)",
  },
  { type: "category", data: "Consults/Referrals" },
  { type: "order", data: "Consult to Social Worker (SW)", value: "" },
  { type: "order", data: "Consult to Indigenous Care Coordinator", value: "" },
  { type: "order", data: "Consult to Palliative Care Nurse", value: "" },
  {
    type: "order",
    data: "Consult to Palliative Care Consultation Team",
    value: "",
  },
  { type: "order", data: "Consult to Pharmacy", value: "" },
  { type: "order", data: "Consult to Spiritual Health Services", value: "" },
];
